global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: "next-demo-1"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["host.docker.internal:4000"]

  - job_name: "next-demo-2"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["host.docker.internal:4020"]

  - job_name: "next-demo-3"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:4030"]

  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
